apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aksofirkat-8577"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aksofirkat-8577"
  template:
    metadata:
      labels:
        app: "aksofirkat-8577"
    spec:
      containers:
        - name: "aksofirkat-8577"
          image: "containerregofirkat.azurecr.io/aksofirkat"
          ports:
          - containerPort: 80