apiVersion: v1
kind: Service
metadata:
    name: "aksofirkat-8577"
    labels:
        app: "aksofirkat-8577"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aksofirkat-8577"