on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: containerregofirkat.azurecr.io
        username: ${{ secrets.acr_containerregofirkat_username }}
        password: ${{ secrets.acr_containerregofirkat_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t containerregofirkat.azurecr.io/aksofirkat:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push containerregofirkat.azurecr.io/aksofirkat:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksofirkat_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks-ofirkata1ed | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks-ofirkata1ed`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks-ofirkata1ed
        container-registry-url: containerregofirkat.azurecr.io
        container-registry-username: ${{ secrets.acr_containerregofirkat_username }}
        container-registry-password: ${{ secrets.acr_containerregofirkat_password }}
        secret-name: aksofirkatdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks-ofirkata1ed
        manifests: |
          manifests/deployment-7.yml
          manifests/service-7.yml
        images: |
          containerregofirkat.azurecr.io/aksofirkat:${{ github.sha }}
        imagepullsecrets: |
          aksofirkatdockerauth
